# ============================================
# PR Analysis Template - ask-devops
# requires Git 'PullRequestContribute' permission to perform this action.
# ============================================
parameters:
- name: foundryEndpoint
  type: string
- name: azureServiceConnection
  type: string

jobs:
- job: AskDevOpsPRAnalysis
  displayName: "Ask DevOps PR Analysis"
  pool:
    vmImage: ubuntu-latest

  steps:
  # Ensure full history so git diff works
  - checkout: pipelines
  - checkout: self
    fetchDepth: 0
    path: sourceRepo
    workspaceRepo: true
    persistCredentials: true

  - task: AzureCLI@2
    displayName: "Run ask-devops against PR diff"
    env:
      PROJECT_ENDPOINT: ${{ parameters.foundryEndpoint }}
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        set -euo pipefail
        echo "###########"
        echo "showing paths"
        pwd
        echo "showing directory contents"
        ls
        echo "############ ############# #############"
        echo "Show content of pipelines Build.SourcesDirectory"
        ls "$(Build.SourcesDirectory)/pipelines"
        
        echo "## Determining PR target branch"
        TARGET_BRANCH="origin/main"
        echo "Target branch: $TARGET_BRANCH"
        echo "## Generating git diff"
        git diff "$TARGET_BRANCH"...HEAD > "$(Build.SourcesDirectory)/pipelines/scripts/changes.txt"

        cd "$(Build.SourcesDirectory)/pipelines/scripts"

        echo "## Diff size"
        wc -l changes.txt

        if [ ! -s changes.txt ]; then
          echo "No changes detected. Exiting."
          echo "No changes detected in PR." > output.md
          exit 0
        fi

        echo "## Running ask-devops.py"
        cd "$(Build.SourcesDirectory)/pipelines/scripts"
        pip install azure-ai-projects --pre
        pip install openai azure-identity python-dotenv
        python ask-devops.py
      
  # Publish PR Summary to PR summary (Markdown rendered)
  #- bash: |
  #    echo "##vso[task.uploadsummary]output.md"
  #  displayName: "Publish analysis to PR summary"
  
  - task: Bash@3
    displayName: "Publish analysis to PR summary"
    inputs:
      targetType: 'inline'
      script: |
        cd "$(Build.SourcesDirectory)/pipelines/scripts"
        pwd
        echo "#####"
        ls
        COMMENT=$(cat output.md)
        echo $COMMENT
  
        ADO_API=$(echo "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1-preview.1")
  
        PR_COMMENT=$(jq --arg comment "$COMMENT" '.comments[0].content = $comment' <<< '{"comments": [{"parentCommentId": 0,"content": "","commentType": 1}],"status": 1}')
  
        curl --request POST "$ADO_API" \
        --header "Content-Type: application/json" \
        --header "Accept: application/json" \
        --header "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
        --data "$PR_COMMENT" \
        --verbose
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.SourcesDirectory)/pipelines/scripts/changes.txt
      artifactName: changes.txt
      condition: always()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.SourcesDirectory)/pipelines/scripts/output.md
      artifactName: output.md
      condition: always()
