
## run when submitting a pull request

## run git diff and save contents to a changes.txt or maybe just in a var

## run the ask-devops.py script, this will be in the pipeline templates repo, so will be available with the template like other scripts.

## show the output in the Pipeline console while it runs this step, but also in a markdown file and/or save in the PR summary.

# ============================================
# PR Analysis Template - ask-devops
# ============================================

trigger: none

pr:
  branches:
    include:
      - main

jobs:
- job: AskDevOpsPRAnalysis
  displayName: "Ask DevOps PR Analysis"
  pool:
    vmImage: ubuntu-latest

  steps:
  # Ensure full history so git diff works
  - checkout: self
    fetchDepth: 0

  - bash: |
      set -euo pipefail

      echo "## Determining PR target branch"
      TARGET_BRANCH="origin/$(System.PullRequest.TargetBranch)"
      echo "Target branch: $TARGET_BRANCH"

      echo "## Generating git diff"
      git diff "$TARGET_BRANCH"...HEAD > changes.txt

      echo "## Diff size"
      wc -l changes.txt

      if [ ! -s changes.txt ]; then
        echo "No changes detected. Exiting."
        echo "No changes detected in PR." > output.md
        exit 0
      fi

      echo "## Running ask-devops.py"
      python ./scripts/ask-devops.py

    displayName: "Run ask-devops against PR diff"

  # Publish PR Summary (Markdown rendered)
  - bash: |
      echo "##vso[task.uploadsummary]output.md"
    displayName: "Publish analysis to PR summary"

  # Optional: upload artifacts for debugging
  - publish: changes.txt
    artifact: pr-diff
    condition: always()

  - publish: output.md
    artifact: pr-analysis
    condition: always()
